<?php

namespace SerieBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SerieCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SerieCommentRepository extends EntityRepository
{
}
