<?php

namespace SerieBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SerieCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SerieCategoryRepository extends EntityRepository
{
}
